### PR TITLE
chore(deps): update @tauri-apps/cli to 1.0.2, closes #76

### LINKED ISSUE #76: `tauri.conf.json` error on `tauri > bundle > windows`: Additional property 'webviewInstallMode' is not allowed
please upgrade the dependency tauri app library version to 1.0.2

### PR DESCRIPTION
**Pull request by FabianLars**

### CODE REVIEW

**Comment by FabianLars** [comment]
ah lol there are no workflows in this repo

**Comment by Arelina** [comment]
Excuse, I have one more question, when I can down it in npm?

**Comment by FabianLars** [comment]
@Arelina When one of the core team members wakes up and publishes it :D

Timezones and Sunday so it may take a while idk.

In the meantime you can use it from github too btw, just change the version to `github:tauri-apps/vue-cli-plugin-tauri` and re-run your package manager's install command.

**Comment by Arelina** [comment]
@FabianLars Thanks😀

**Comment by Arelina** [comment]
@FabianLars I'm so sorry to bother you again, when I use the github:tauri-apps/vue-cli-plugin-tauri. In the dev mode, I can't enter the localhost:8080 and my app is white screen.but in pro mode is no problem.

**Comment by FabianLars** [comment]
Are there any errors in the devtools console (right click on the window -> "inspect")? Or in the terminal where you executed `npm run tauri:dev`?

Can you access localhost:8080 in your browser?

**Comment by Arelina** [comment]
It has nothing error.
and I can't access localhost:8080 in browser.

**Comment by Arelina** [comment]
My steps
1. vue create app
2. chose vue3
3. vue add tauri
4. edit the vue-cli-plugin-tauri Url github:tauri-apps/vue-cli-plugin-tauri
5. npm install 
6. npm run tauri:serve

**Comment by FabianLars** [comment]
Yeah i can reproduce it. Super weird that according to the terminal output it successfully started 🤔 Also `npm run serve` works fine too.
I'm not a vue guy at all so i don't know if i can figure it out 😂

**Comment by FabianLars** [comment]
ayyy i forgot to ping @lucasfernog (both for the new release and this issue above)

**Comment by lucasfernog** [comment]
This is a regression :( I totally forgot about this plugin and changed the CLI to be blocking :|

**Pull request merged**
